Upgrade to Scala 2.13 and Spark to 3.2.1
* Updated several libraries as well
* Solved `java.lang.NoSuchMethodError: io.netty.buffer.PooledByteBufAllocator.<init>(ZIIIIIIZ)V` by introducing a dependency override